require('my_plugins.status-line').setup()
require('my_plugins.tab-line').setup()
require('my_plugins.pinned-files').setup()
require('my_plugins.notes').setup()
require('my_plugins.floating-terminal').setup()
require('my_plugins.godot-project-picker').setup()
require('my_plugins.session-picker').setup()
