local gh = require("utils.gh")
vim.pack.add({ gh("stevearc/aerial.nvim") })
require("aerial").setup({
    layout = {
      default_direction = "left"
    },
    keymaps = {
        ["?"] = "actions.show_help",
        ["g?"] = "actions.show_help",
        -- ["<2-LeftMouse>"] = "actions.jump",
        ["<C-v>"] = "actions.jump_vsplit",
        ["<C-s>"] = "actions.jump_split",
        ["l"] = "actions.scroll",
        ["<M-l>"] = "actions.jump",
        ["<M-j>"] = "actions.down_and_scroll",
        ["<M-k>"] = "actions.up_and_scroll",
        ["{"] = "actions.prev",
        ["}"] = "actions.next",
        ["[["] = "actions.prev_up",
        ["]]"] = "actions.next_up",
        ["q"] = "actions.close",
        ["<M-q>"] = "actions.close",
        ["o"] = "actions.tree_toggle",
        ["za"] = "actions.tree_toggle",
        ["O"] = "actions.tree_toggle_recursive",
        ["zA"] = "actions.tree_toggle_recursive",
        -- ["l"] = "actions.tree_open",
        ["zo"] = "actions.tree_open",
        ["L"] = "actions.tree_open_recursive",
        ["zO"] = "actions.tree_open_recursive",
        ["h"] = "actions.tree_close",
        ["zc"] = "actions.tree_close",
        ["H"] = "actions.tree_close_recursive",
        ["zC"] = "actions.tree_close_recursive",
        ["zr"] = "actions.tree_increase_fold_level",
        ["zR"] = "actions.tree_open_all",
        ["zm"] = "actions.tree_decrease_fold_level",
        ["zM"] = "actions.tree_close_all",
        ["zx"] = "actions.tree_sync_folds",
        ["zX"] = "actions.tree_sync_folds",
    },
    filter_kind = {
        -- "Array",
        -- "Boolean",
        "Class",
        "Constant",
        "Constructor",
        "Enum",
        "EnumMember",
        "Event",
        "Field",
        "File",
        "Function",
        "Interface",
        -- "Key",
        "Method",
        "Module",
        "Namespace",
        -- "Null",
        -- "Number",
        -- "Object",
        -- "Operator",
        -- "Package",
        -- "Property",
        -- "String",
        -- "Struct",
        -- "TypeParameter",
        "Variable",
    },
    highlight_on_jump = 150,
    highlight_on_hover = true,
    manage_folds = true,
    link_folds_to_tree = false,
    link_tree_to_folds = false,
    close_on_select = true,
    show_guides = true,
    -- on_attach = function(bufnr)
    --     -- Jump forwards/backwards with '{' and '}'
    --     vim.keymap.set("n", "{", "<cmd>AerialPrev<CR>", { buffer = bufnr })
    --     vim.keymap.set("n", "}", "<cmd>AerialNext<CR>", { buffer = bufnr })
    -- end,
})
vim.keymap.set("n", "<M-a>", "<cmd>AerialToggle<CR>")
-- vim.keymap.set("n", "<leader>a", "<cmd>AerialToggle float<CR>")
