require("plugins.nvim-web-devicons")
require("plugins.treesitter")
require("plugins.treesitter-textobjects")
require("plugins.lsp")
require("plugins.blink")
require("plugins.gitsigns")
require("plugins.mini-pick")
require("plugins.mini-files")
require("plugins.mini-operators")
require("plugins.mini-pairs")
require("plugins.mini-surround")
-- require("plugins.nvim-org-mode")
require("plugins.quicker")
require("plugins.aerial")
require("plugins.render-markdown")
require("plugins.which-key")
-- Load theme last
require("plugins.theme")
